# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d59561909fa774f5e3d32bbbd9579acb648747327b60947953e71ae3b7d7c22f5a4118d7d3ceeb8e222f9d6f745e4a46293b576d1033fc27cceca422e3c7f409

test:
  secret_key_base: e1b0378b1616022ddaf4efc4381be53e0edc050a978d72c4a12d119a74b4ada2adb09dafdc3814423ba8c9cc2c60be131d510249d891791a395ecaeeb963598c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
